FROM node:20-alpine

WORKDIR /app

# código já compilado e dependências já presentes no contexto
COPY package.json ./
COPY node_modules ./node_modules
COPY prisma ./prisma
COPY dist ./dist

ENV NODE_ENV=production

RUN npx prisma generate

CMD ["node", "dist/scripts/cron.js"]